version: '3.8'

services:
  php:
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - mynetwork
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-restaurants-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:             